sonar.projectKey=Karolina91_ProjetoI-Individual-GCES-2026.1
sonar.organization=karolina91
sonar.sources=server
sonar.exclusions=server/node_modules/**,server/tests/**
sonar.tests=server/tests
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info